/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as frontPostsIndexImport } from './routes/(front)/posts/index'
import { Route as frontPostsPostIdImport } from './routes/(front)/posts/$postId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const frontPostsIndexRoute = frontPostsIndexImport.update({
  id: '/(front)/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const frontPostsPostIdRoute = frontPostsPostIdImport.update({
  id: '/(front)/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/(front)/posts/$postId': {
      id: '/(front)/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof frontPostsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/(front)/posts/': {
      id: '/(front)/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof frontPostsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts/$postId': typeof frontPostsPostIdRoute
  '/posts': typeof frontPostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts/$postId': typeof frontPostsPostIdRoute
  '/posts': typeof frontPostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(front)/posts/$postId': typeof frontPostsPostIdRoute
  '/(front)/posts/': typeof frontPostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/posts/$postId' | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/posts/$postId' | '/posts'
  id: '__root__' | '/' | '/about' | '/(front)/posts/$postId' | '/(front)/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  frontPostsPostIdRoute: typeof frontPostsPostIdRoute
  frontPostsIndexRoute: typeof frontPostsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  frontPostsPostIdRoute: frontPostsPostIdRoute,
  frontPostsIndexRoute: frontPostsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/(front)/posts/$postId",
        "/(front)/posts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/(front)/posts/$postId": {
      "filePath": "(front)/posts/$postId.tsx"
    },
    "/(front)/posts/": {
      "filePath": "(front)/posts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
